{% set name = "zen-engine" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zen_engine-{{ version }}.tar.gz
  sha256: 2aa77c40cf73a0b1a67a1c9dbbd9f06cba67c921676422ecdeeb3aeb716988c6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.14,<0.15                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
    - rust
  run:
    - python

test:
  imports:
    - zen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gorules.io/
  summary: Open-Source Business Rules Engine
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carinapeng
    - janjagusch
