{% set name = "zen-engine" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zen_engine-{{ version }}.tar.gz
  sha256: f26fadcdda88d3a04e83c5e6fe3191bafafd3074cab1f2abf9d125c2c197d6ab

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.14,<0.15                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
    - rust
    - git  # [win]
  run:
    - python

test:
  imports:
    - zen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gorules.io/
  summary: Open-Source Business Rules Engine
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carinapeng
    - janjagusch
    - ivergara
    - nick-harmening
