schema_version: 1

context:
  name: zen-engine
  version: "0.50.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/zen_engine-${{ version }}.tar.gz
  sha256: 54e20a2393446edb5aea9522b33567cc7bcc6b4eb1d898e7b6cc3470f8e76840

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv
  dynamic_linking:
    missing_dso_allowlist:
      - if: win
        then: "*/api-ms-win-core-winrt-*.dll"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
    - rust
    - if: win
      then: git
  run:
    - python

tests:
  - python:
      imports:
        - zen
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Open-Source Business Rules Engine
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://gorules.io/

extra:
  recipe-maintainers:
    - carinapeng
    - janjagusch
    - ivergara
    - nick-harmening
