schema_version: 1

context:
  name: zen-engine
  version: 0.50.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/zen_engine-${{ version }}.tar.gz
  sha256: a562e0af22312e86174de36e5b1891334ea7863db23fd60a7abbfb4afc519fb3

build:
  number: 1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv
  dynamic_linking:
    missing_dso_allowlist:
      - if: win
        then: "*/api-ms-win-core-winrt-*.dll"

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: crossenv
    - if: build_platform != target_platform
      then: maturin >=0.14,<0.15
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
    - rust
    - if: win
      then: git
  run:
    - python

tests:
  - python:
      imports:
        - zen
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Open-Source Business Rules Engine
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://gorules.io/

extra:
  recipe-maintainers:
    - carinapeng
    - janjagusch
    - ivergara
    - nick-harmening
